# TCL File Generated by Component Editor 18.1
# Mon Jun 29 17:39:33 ICT 2026
# DO NOT MODIFY


# 
# urx "urx" v1.0
#  2026.06.29.17:39:33
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module urx
# 
set_module_property DESCRIPTION ""
set_module_property NAME urx
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME urx
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_slave_urx
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_slave_urx.v VERILOG PATH avalon_slave_urx.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point conduit_end_1_1_1
# 
add_interface conduit_end_1_1_1 conduit end
set_interface_property conduit_end_1_1_1 associatedClock clock
set_interface_property conduit_end_1_1_1 associatedReset ""
set_interface_property conduit_end_1_1_1 ENABLED true
set_interface_property conduit_end_1_1_1 EXPORT_OF ""
set_interface_property conduit_end_1_1_1 PORT_NAME_MAP ""
set_interface_property conduit_end_1_1_1 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_1_1_1 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_1_1_1 rx new_signal Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_1_1_1
# 
add_interface avalon_slave_1_1_1 avalon end
set_interface_property avalon_slave_1_1_1 addressUnits WORDS
set_interface_property avalon_slave_1_1_1 associatedClock clock
set_interface_property avalon_slave_1_1_1 associatedReset reset
set_interface_property avalon_slave_1_1_1 bitsPerSymbol 8
set_interface_property avalon_slave_1_1_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_1_1_1 burstcountUnits WORDS
set_interface_property avalon_slave_1_1_1 explicitAddressSpan 0
set_interface_property avalon_slave_1_1_1 holdTime 0
set_interface_property avalon_slave_1_1_1 linewrapBursts false
set_interface_property avalon_slave_1_1_1 maximumPendingReadTransactions 1
set_interface_property avalon_slave_1_1_1 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_1_1_1 readLatency 0
set_interface_property avalon_slave_1_1_1 readWaitTime 1
set_interface_property avalon_slave_1_1_1 setupTime 0
set_interface_property avalon_slave_1_1_1 timingUnits Cycles
set_interface_property avalon_slave_1_1_1 writeWaitTime 0
set_interface_property avalon_slave_1_1_1 ENABLED true
set_interface_property avalon_slave_1_1_1 EXPORT_OF ""
set_interface_property avalon_slave_1_1_1 PORT_NAME_MAP ""
set_interface_property avalon_slave_1_1_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_1_1_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_1_1_1 address address Input 9
add_interface_port avalon_slave_1_1_1 read read Input 1
add_interface_port avalon_slave_1_1_1 readdata readdata Output 32
add_interface_port avalon_slave_1_1_1 write write Input 1
add_interface_port avalon_slave_1_1_1 writedata writedata Input 32
add_interface_port avalon_slave_1_1_1 readdataValid readdatavalid Output 1
set_interface_assignment avalon_slave_1_1_1 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_1_1_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_1_1_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_1_1_1 embeddedsw.configuration.isPrintableDevice 0

